# Generated by Django 3.2.13 on 2022-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_image', models.ImageField(null=True, upload_to='')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=39)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
