# Generated by Django 3.2.13 on 2022-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBankInformation',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(max_length=255, null=True)),
                ('bank_id', models.IntegerField()),
                ('bank_branch', models.IntegerField()),
                ('bank_secret', models.TextField(null=True)),
            ],
        ),
    ]
