# Generated by Django 3.2.13 on 2022-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_supplier', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
    ]
